spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/jwt_security
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  sql:
    init:
      mode: always
jwt:
  public:
    key: classpath:app.pub
  private:
    key: classpath:app.key
